### ISSUE TITLE
Design Question

### ISSUE THREAD

**Issue by J-8** [GroundApps/ShoppingList#11]
I have a couple of things that I dont think are perfect such as the swiping to dismiss. I don't think it works that well.
### I would be happy for any suggestions how to elegantly solve it.

My idea / suggestion:
- add a checkmark to each row, so you can mark each item as checked
- the clear list button in the options menu removes only checked items
### Thanks for your feedback!

Also if anyone has any idea for a more elegant icon, I would be happy to hear! :)

**Comment by ghost** [comment]
That are good points.
But also i think
- create list in the app
- share list
- change name of list
- remove count / so you can use the list for other thinks too

**Comment by ghost** [comment]
Maybe I can help you with the PHP Part

**Comment by J-8** [comment]
Good morning:)
Could you open an issue with each suggestion and elaborate a bit more? Especially the "share list" part. Thanks!
