### ISSUE TITLE
Share List

### ISSUE THREAD

**Issue by ghost** [GroundApps/ShoppingList#12]
Ok, you create a List. 
There is a user that down have access to your Server, so you want to share the list.
Then you can select how => Mail, WhatsApp, etc
He get a simpel Message in this format:

List
 [ ] Eggs
 [ ] Meat
 [ ] Pasts
He will not see it as a list, only as a simple TextMessage

**Comment by J-8** [comment]
Love it!
Danke!

**Comment by ghost** [comment]
Your Are Welcome
