### ISSUE TITLE
Settings -> Authkey description misleading

### ISSUE THREAD

**Issue by ecw2-4** [GroundApps/ShoppingList#13]
In the android app, under "settings", the comment underneath "AuthKey" reads now 

> Please provide your authentication token (defined in api.php)

But shouldn't it be:

> Please provide your authentication token (defined in **config.php**)

**Comment by J-8** [comment]
You are right! Thanks!
The php backend changed after the app was uploaded to fdroid, but we will fix this (among a lot of other things) with the next update.
For now, maybe you want to do the changes yourself and send a merge request?

**Comment by J-8** [comment]
Fixed.
