### ISSUE TITLE
[Request] Plus/Minus buttons on item quantity

### ISSUE THREAD

**Issue by ghost** [GroundApps/ShoppingList#17]
I think it would be helpful to have buttons that one could press to increment/decrement the number of items needed. That way one does not have to tap on the number box, wait for the keyboard to pop up, hit backspace, and then press the number desired.

**Comment by J-8** [comment]
I have also played with that idea, however how would that work with #18 ? How would the symbols appear? Or are they always there even if the quantity is not displayed?
Also we will have to play around a bit with the design, so it does not get to cluttered. It certainly would help with another idea ( #11 ).
Thanks!

**Comment by ghost** [comment]
I'm not sure of the best design: I was speaking only on a UX point of view. A functional solution might be to just add the +/- widgets on either side of the number entry form (and maybe take it to a new line if room is needed). I'm not sure how it would contribute to clutter as it's just in the "add item" dialogue.

Of course, there are probably better ways to design it.

**Comment by J-8** [comment]
We will just have to experiment ;)

**Comment by J-8** [comment]
Implemented. Really like it. Thanks!
