### ISSUE TITLE
Do not show single item entries.

### ISSUE THREAD

**Issue by ghost** [GroundApps/ShoppingList#18]
It might be best design to default to an unspecified quantity that does not show in the list: Only when multiples are needed (and specified by the user) will a number show up. Otherwise, there's a bunch of 1s on the list that clutter up the interface and make it more difficult to discern when multiples are needed.

Thanks for the great app! I love it!

**Comment by J-8** [comment]
Thanks for your feedback! Good idea! I love ideas that are easy to implement :)

**Comment by J-8** [comment]
Implemented.
