### ISSUE TITLE
App Icon

### ISSUE THREAD

**Issue by jklmnn** [GroundApps/ShoppingList#2]
The app icon is black with transparent background which makes it invisible in the default Android app drawer.

**Comment by J-8** [comment]
Yeah, I noticed that too. That's the problem if you only test on one device ::-D
I'll definitely fix that.
Thanks!

**Comment by ghost** [comment]
![shoppinglist](https://cloud.githubusercontent.com/assets/7816755/9427589/01bae91c-4986-11e5-946f-a6aa9fe538aa.png)
Create a Icon what do you think?

**Comment by jklmnn** [comment]
I would prefer bars with round corners instead of long and slim ovals.

**Comment by J-8** [comment]
I agree. @beli3ver Whenever you have the time, could you create one like that? Thanks:)

**Comment by ghost** [comment]
I will try in blue vor other color

**Comment by jklmnn** [comment]
I think the blue from your first suggestion is fine.

**Comment by J-8** [comment]
I took the one from @beli3ver for now, so we can at least fix this. Thanks!

**Comment by ghost** [comment]
I will create next weak a new one

**Comment by J-8** [comment]
I actually like it, so there is no need to hurry!
