### ISSUE TITLE
"favourites" star when editing items

### ISSUE THREAD

**Issue by the0ne** [GroundApps/ShoppingList#20]
an item can currently only be added to favourites when creating it.
if user realizes that an already existing item should be a favourite there's no way to mark it.
please add the "favourites" star to the edit list item dialog.

**Comment by ghost** [comment]
Add the next update you will have favourites, important and stared

**Comment by J-8** [comment]
Thanks for your feedback! The code exists and it will be implemented next time.

**Comment by J-8** [comment]
Has been implemented. It is now a simple label saying "Favorite". When you mark it as favorite, it has a blue glow.
