### ISSUE TITLE
Request: select multiple items in favorites at once (checkboxes)

### ISSUE THREAD

**Issue by fajabird** [GroundApps/ShoppingList#21]
I'm using OI-ShoppingList for many years now but I like your idea of a synchronized list across multiple devices and using own servers. I really would like to make this project really useful. Here is my first out of multiple suggestions:

When I prepare my shopping list I like to open up my favorites list and while I'm looking around (e.g. in the refrigerator) I select what I need to buy. When I'm done I click on "OK" and all items are copied to the shopping list at once. After that I modify some items count numbers (this is already implemented but not optimal - see my next suggestion issue).

So I suggest to replace the select boxes with checkboxes to allow multiple selection.

**Comment by J-8** [comment]
Has been implemented.
