### ISSUE TITLE
keyboard enhancements

### ISSUE THREAD

**Issue by fajabird** [GroundApps/ShoppingList#22]
When creating an new item keyboard should pop up automatically. At the moment I have to touch on "Artikel" (I'm from germany). 

The same applies to when I want to modify the count value for an item on the list. At the moment I have to touch on the "number" to get the keyboard. Keyboard should pop up automatically AND the current value should be preselected, so when I enter "2" I get "2". At the moment I get "12" because cursor is behind the current value.

**Comment by J-8** [comment]
Morgen!
Thanks for you feedback!
And I, as well as several others, agree that the current behavior is not very elegant.

**Comment by J-8** [comment]
Done! Thanks!
