### ISSUE TITLE
swipe to puncture

### ISSUE THREAD

**Issue by fajabird** [GroundApps/ShoppingList#24]
You already mentioned that the currect swipe to dismiss is not perfect - I agree :-)

My suggestion: swipe to puncture (durchstreichen):

Programatically you have to manage 2 distinct lists:
1. active items
2. deactivated items
1. User swipes an item in the first list (=active items). 
2. Items gets punctured and sorted to the back, i.e. into the second list (=deactivated items, same sort rules, i.e. by shelf-number + alphabetically).
3. Clear list button only removes all punctured items (i.e. clears the second list).
4. Swiping on an punctured items will "unpuncture" it (i.e. move it back to the first list).

Of course you could do the same with checkmarks instead of puncture the items text. This is only a question of preference and coding effort.

**Comment by J-8** [comment]
Thanks for your suggestion!
The checkmark thing is easier, so at the moment I would really prefer that;)
After all, it is just a matter of design and what works with what. I am incredibly unsure about that, so I am always happy to hear suggestions!

**Comment by J-8** [comment]
I really liked you idea, make it feel more like a real list.
For now we implemented tap to puncture.
Thanks!
