### ISSUE TITLE
proper offline mode

### ISSUE THREAD

**Issue by fajabird** [GroundApps/ShoppingList#26]
I think the app should work in offline mode the same way it works in online mode. At the moment offline mode does even not allow to swipe away items - this offline mode is not usable at the moment. In addition, when you start the app while online and you go offline for some reason you get the "cannot connect" error upon first action on your list.

**Comment by J-8** [comment]
The problem about offline mode is that I have no idea how to handle conflicts with other users efficiently. But I will look into it.
Really appreciate your feedback!

**Comment by J-8** [comment]
For now you can check items when in offline mode. Everything else however needs a lot more engineering, something I am just not able to do at the moment.
