### ISSUE TITLE
API Level

### ISSUE THREAD

**Issue by jklmnn** [GroundApps/ShoppingList#3]
Is it possible to make the app compatible to lower api levels (my personal wish would be 18 ;) )?

**Comment by J-8** [comment]
I was fearing the question would come... ;) Probably yes, as far as I know the libraries I use are compatible. Honestly, I never thought anyone else would use it, so I pretty much did it for myself and family.
I will get to it as soon as I have to time. Thanks for your comment!

**Comment by jklmnn** [comment]
You just can lower the `minSdkVersion` in the build.gradle file and look how long it compiles. That will be your lowest api level without changing your code.

**Comment by J-8** [comment]
Alright, it looks like we can go down to 14. This is only limited by the FAB implementation.

**Comment by ghost** [comment]
14 I think is more then enough!

**Comment by jklmnn** [comment]
14 is great!
