### ISSUE TITLE
[enhancement] update icon to make it visible on a dark wallpaper

### ISSUE THREAD

**Issue by k3a** [GroundApps/ShoppingList#37]
The icon is basically invisible on my dark space wallpaper. :)
Not a big deal but including some lighter parts in the icon (for example lighter pixels around all dark pixels) would make it look ok on light as well as dark backgrounds.

**Comment by J-8** [comment]
Thanks for your feedback! This was fixed in the new version. Due to problems with fdroid I currently cannot push the update.
