### ISSUE TITLE
Picked-Up Items

### ISSUE THREAD

**Issue by ghost** [GroundApps/ShoppingList#40]
It would be nice if once the items had been picked up and put into the basket you could use a swipe-to-the-right gesture to slide the item off the screen.

This way the font could stay nice and readable , the list would be reduced as the shopping is done and unavailable items would be left behind on the list for the next shopping trip or store.

This may have been fixed in client version > 1.0 but I couldn't get version 1.1 to work.

**Comment by J-8** [comment]
Thanks for your feedback! I am going home tomorrow and will finally have time to fix the update problem with fdroid. V 1.1 behaves differently, you cross items of the list. However if you want, open an issue that you want the swiping for the list, and I'll try to make an option for that;)

**Comment by ghost** [comment]
Thanks @J-8 , the main issue was all items disappearing when I was unable to complete a shopping trip and being forgotten.

Either a tick box or sliding completed items are both good , I just thought the sliding may be easier to see and use.

Look forward to seeing the new version and thanks for writing such a cool tool!

**Comment by J-8** [comment]
Hey! Have you tried the new version yet? Does it work?

**Comment by ghost** [comment]
Not yet , as of 2015-09-24 0728 , F-Droid is still showing version 1.1 from 2015-09-04
I will upgrade as soon as it updates though.

**Comment by ghost** [comment]
Upgraded to version 1.3 via F-Droid and it no longer connects to the server.

I just see a spinning white ball thingy.

Upgraded backend to latest git version - 03923e5 , tried Master and Expirmental branches , still unable to connect.

My wife's device is still using client version 1.0 and that still connects and works.

**Comment by J-8** [comment]
That is really weird. Especially because after 5 seconds it should reach the connect timeout. So it probably has to do with somthing else...
Does the server show any connects from your device?

The thing is... app 1.0 does not work with the new backend version because the array names have changed. The question is, why it does for your wife.
I've just tried it with the new backend and app v1.0, which fails to work.
Could you check in CONSTANTS.php if BACKEND_VERSION on the top of the file is definded?

v1.3 should work just fine with [release 1](https://github.com/GroundApps/ShoppingList_Backend/releases) of the backend, no need for the experimental.

**Comment by ghost** [comment]
I found the problem with my setup.
I only allow specific User-Agents to this VirtualHost so needed to add it 'ShoLiApp' to the list.
I also switched back to the Master branch and now my version 1.3 started working.
Upgraded the wife to 1.3 and its working perfectly for her , I didn't do a refresh when she was on 1.0 so perhaps thats why it looked like it was working. 
In CONSTANTS.php I am seeing define('BACKEND_VERSION', 1.0);

Back to the original question , we can now click an item and it gets 'crossed out' , when my wife did this to some items and then refreshed the 'crossed out' items returned to being not 'crossed out' , when I refreshed I do not see her 'crossed out' items.

Thanks for the updates and support.

**Comment by J-8** [comment]
Ah good to know. Another thing for the wiki.

The synchronization of crossed out items is defined in the milestone v1.4.

Sure, of course!
