### ISSUE TITLE
Remember all items for completion

### ISSUE THREAD

**Issue by mcepl** [GroundApps/ShoppingList#41]
When using `trolly` there is one (and perhaps only one ;)) advantage against this application: it remembers all items ever entered and suggests them for completion. So, currently, I don't have to type more than a few characters for frequently bought items (e.g., just 'ml' for 'mléko” (milk in Czech)).

**Comment by J-8** [comment]
Thanks, I like the idea! Will have to look into that how it works best.

**Comment by J-8** [comment]
Implemented. Incredibly useful idea! Thanks!
