### ISSUE TITLE
Mismatching tag

### ISSUE THREAD

**Issue by ghost** [GroundApps/ShoppingList#42]
Latest tag is v1.2, but build.gradle still says `versionCode 2` and `versionName "1.1"`.

**Comment by J-8** [comment]
True. Missed that when I hurried to update. Still a lot to learn...

**Comment by jklmnn** [comment]
@J-8 you should fix this since it is preventing f-droid from building https://f-droid.org/wiki/page/org.janb.shoppinglist#1.2
I have created a pull request that should fix that: https://github.com/GroundApps/ShoppingList/pull/44

**Comment by J-8** [comment]
I did not know that it would not build. Good to know. Thanks. I'll retag now.
