### ISSUE TITLE
1.3 isn't able to build.

### ISSUE THREAD

**Issue by jklmnn** [GroundApps/ShoppingList#47]
App version 1.3 could not be built from F-Droid. View the [wiki](https://f-droid.org/wiki/page/org.janb.shoppinglist#1.3) and the [build log](https://f-droid.org/wiki/page/org.janb.shoppinglist/lastbuild_4).
The reason is that material_dialogs could not be downloaded. I could recreate this issue locally. You may try to include this into your repo.

**Comment by J-8** [comment]
I'll check that when I get home. Thanks for the info!

**Comment by J-8** [comment]
Seeing that v1.2 was never used, I will fix this and retag as v1,2.
Thanks again for the info. Another thing I never read anywhere.

**Comment by J-8** [comment]
Or not. That one has already been disabled. So I will retag as v1.3, versionCode 4.

**Comment by J-8** [comment]
Should build now.
