### ISSUE TITLE
Missing Translation for Predictions Preference 

### ISSUE THREAD

**Issue by J-8** [GroundApps/ShoppingList#49]
No German translation for Category 'Predictions' and Preference 'Clear Predictions'

**Comment by ghost** [comment]
There is a translation look here:

https://github.com/GroundApps/ShoppingList/blob/master/app/src/main/res/values-de/strings.xml

```
<string name="preferences_category_predictions">Vorschläge</string>
<string name="preferences_action_clear_predictions">Vorschläge löschen</string>
<string name="toast_predictions_cleared">Vorschläge gelöscht</string>
```
