### ISSUE TITLE
"Es wurde kein Header mit der Versionsinfo gefunden."

### ISSUE THREAD

**Issue by Black-Fry** [GroundApps/ShoppingList#50]
Hi guys (great project, but little lack of documentations),
I previously updated the app from version 1.1 to 1.3!
After restarting the app i wasnt able to create any new entries within my shopping-list and instead received the following message: "Es wurde kein Header mit der Versionsinfo gefunden."
I am still able to open "stored versions". 
Furthermore I updated each files of the backend manually - same result.
Finally I deleted my My-SQL-DB and re-ran install.php - unfortunately I am getting the same error-message (see above).

Could you help me, please? I dont know, what else I may be doing wrong!?

**Comment by J-8** [comment]
Hey! Darn, I forgot to translate that. It means that no header with the version info could be found in the reply. Does your server support setting custom headers? If you check out api.php that's what happens in one of the first lines. We'll have to add a check for that then.

**Comment by Black-Fry** [comment]
Hi J! Well its not the translation Im having trouble with (German). It really seems to be my provider (1und1, php-ver: 5.5.28) who is somehow messing around with the header()-function. I added those lines into api.php fur debugging-purposes:

(...)
    include "CONSTANTS.php";

```
if (isset($_GET['showDetails']))
{
    print_r (headers_list());
    echo "<br>";
    print_r (headers_sent());
    echo "<br>";
header("ShoLiBackendVersion: ".BACKEND_VERSION);
    print_r (headers_list());
    echo "<br>";
    print_r (headers_sent());
    echo "<br>";
    echo "ShoLiBackendVersion: ".BACKEND_VERSION;
    echo  "<br>";
}   
```

 if(!function_exists('hash_equals')) {
(...)

And the 1&1-output is (if showDetails is set):
Array ( [0] => X-Powered-By: PHP/5.5.28 [1] => Content-type: text/html ) 
1
Array ( [0] => X-Powered-By: PHP/5.5.28 [1] => Content-type: text/html ) 
1
ShoLiBackendVersion: 1

If I am running the same file and backend in another environment (custom and private webserver), I get this result:
Array ( [0] => X-Powered-By: PHP/5.4.41-0+deb7u1 ) 

Array ( [0] => X-Powered-By: PHP/5.4.41-0+deb7u1 [1] => ShoLiBackendVersion: 1 ) 

ShoLiBackendVersion: 1
{"type":5002,"content":"Authentication failed."}

..second looks better, doesnt it?

I would prefer to use it, unfortunately this webserver is SSLed with a self-signed certificate. Locating the app towards this server makes the app try to connect for ages.

**Comment by J-8** [comment]
Sadly I have no idea what the issue could be. Can you check the logs what happens when you try to connect? Error messages on the server? 

If we can't fix this you will probably have to wait for the next version which will implement the memorizingTrustManager for Self-signed certificates.

Maybe someone else has another idea?

**Comment by Black-Fry** [comment]
..well that was as easy as frustrating! the reason for the error is a leading space pefore "<?php" within api.php of the backend.
this generates a client-sided output. therefore the header()-calls are misleaded.
after removing that single space everything went fine

**Comment by J-8** [comment]
Glad you found it yourself!
Where is the leading space exactly?

**Comment by Black-Fry** [comment]
see my re-commented comment :-)

for declaration: that leading space is ignored while the file ran at my own (ssled, see above) webserver. imho 1und1 does not execute php-code but wraps it as cgi. see: https://hilfe-center.1und1.de/hosting/1und1-hosting-c10085285/skript--und-programmiersprachen-c10082634/php-c10082686/bedienung-c10082739/http-authentifizierung-mit-php-a10782437.html . so not all users will run into that acceident - at least all using 1und1-webspace should do.

**Comment by J-8** [comment]
Awesome, thanks for the catch.
