### ISSUE TITLE
Version 1.3 doesn't connect to server. Version 1.1 does.

### ISSUE THREAD

**Issue by cyrg2012** [GroundApps/ShoppingList#53]
The difference seems to be that in version 1.1 I have to put the full url.
Version 1.3 reports that the server refuse the connection, nginx access log shows that the app gets a 403 on the directory, maybe the app doesn't ask for api.php?
Sorry for my bad english and thanks for the app.

**Comment by J-8** [comment]
Hey! No te preocupes, te entendemos bien :)

The 403 error gets thrown on which page? I guess it says somewhere which page was accessed?
Have you tried it without appending api.php at the end ("example.org/sholi/")? Could be that I messed up something and that actually .../api.php/ gets requested.

**Comment by cyrg2012** [comment]
If the host in the app is host/sholi, the 403 is on host/sholi/
host/sholi/api.php gets me host/sholi/api.php/

**Comment by J-8** [comment]
Okay, the second issue I have corrected.
But the first one I really cannot understand. Can you open it in the browser?

**Comment by cyrg2012** [comment]
It probably has something to do with nginx... I'm new to it. I'll try different configs this weekend and see whats happening. Probably missing index, try_files or something...
I can't open the directory (get's me a 403) but if I point at the api.php I get the authentication error, so it's working...
Oh by the way if the host is host/sholi/ the log shows /host/sholi//

**Comment by J-8** [comment]
Sadly I have no experience with nginx.
The two things you have mentioned are fixed in the new version. Thanks :)

**Comment by cyrg2012** [comment]
Ok the problem was with my server config. So I think this issue is closed. Thanks for your time and app!

**Comment by J-8** [comment]
Glad you could figure it out:) 

Maybe you could tell what the issue was, so those who run into the same problem will know what to do.
