### ISSUE TITLE
Connection error using Motorola moto e - Android 5.1

### ISSUE THREAD

**Issue by Dalan94** [GroundApps/ShoppingList#54]
When using this phone the phone try indefinitely to download the shopping list. There is no error message. It's not a server problem because it run well with another phone and the same parameters.

**Comment by J-8** [comment]
Hey!
What do the server logs say? Are there any connects?

**Comment by Dalan94** [comment]
How can I access to the server log ?

**Comment by J-8** [comment]
The server on which you put the backend should have logs about all connections made to it.
I am running Debian and Apache for example, and my logs (access.log and error.log) are under /var/log/apache2/

It really depends on your server configuration...
Which oparating system do you use and which webserver is running?

**Comment by Dalan94** [comment]
I find them. I have nothing in the log when I try with the Motorola. But I have something in the error.log when I'm connecting with the other phone :

```
[Sun Oct 04 14:53:36.763884 2015] [:error] [pid 22639] [client xxx] PHP Notice:  Undefined index: item in /var/www/shoppinglist/api.php on line 13
[Sun Oct 04 14:53:36.763948 2015] [:error] [pid 22639] [client xxx] PHP Notice:  Undefined index: count in /var/www/shoppinglist/api.php on line 14
[Sun Oct 04 14:53:36.763957 2015] [:error] [pid 22639] [client xxx] PHP Notice:  Undefined index: jsonArray in /var/www/shoppinglist/api.php on line 15
[Sun Oct 04 14:53:37.045510 2015] [:error] [pid 22639] [client xxx] PHP Notice:  Undefined index: item in /var/www/shoppinglist/api.php on line 13
[Sun Oct 04 14:53:37.045563 2015] [:error] [pid 22639] [client xxx] PHP Notice:  Undefined index: count in /var/www/shoppinglist/api.php on line 14
[Sun Oct 04 14:53:37.045571 2015] [:error] [pid 22639] [client xxx] PHP Notice:  Undefined index: jsonArray in /var/www/shoppinglist/api.php on line 15
```

I don't know if there is a connection.

**Comment by J-8** [comment]
The errors in the log do not mean anything really.
What would be helpful however would be to know what is logged in the acces.log (or something like that) when you try to get the data.
I is also weird that there is no connection timeout. I am a bit puzzled.

**Comment by Dalan94** [comment]
There is nothing in acces.log when I use the Motorola phone.
Furthermore the phone do the same thing (ie search indefinitely) when I set a wrong address. 
But the app use a lot of data (250 Mo in one night !!!).

**Comment by J-8** [comment]
That... is highly confusing. The only thing that is requested and sent is a bit of json.
And I  really don't know why it keeps trying to connect. There is a timeout of 5 seconds. 
Which version are you using? Do you have a firewall enabled on your phone?

**Comment by Dalan94** [comment]
I doesn't work with all the version in fdroid and I don't have a firewall. But I try to debug myself with Android Studio and it work with the git version... So I don't know the difference. Maybe it's the apk file or the Android API version.

**Comment by J-8** [comment]
It just hit me why it uses so much data....
You are using the data from github? I was testing how to check if there is an update for the backend and the check interval is 5 seconds.... so that is why...

**Comment by Dalan94** [comment]
I don't know what I can say...
The back-end use the first release.
And the check for update is not enable in the last release so that can't be that which use the data.
Furthermore I try to compile the version 1.3 and it run correctly on the phone while the f-droid version doesn't.

**Comment by J-8** [comment]
I am out of ideas... We will have to check after the next update. Sorry about that...
