### ISSUE TITLE
Error messages have to be more specific

### ISSUE THREAD

**Issue by J-8** [GroundApps/ShoppingList#6]
Error messages are vague and missleading. They should be more specific on the actual error. Including errors with the backend.

**Comment by ecw2-4** [comment]
I agree with this. In my case, the app can't connect, but I can do everything successfully with "curl --data "auth=password&item=&count=&function=listall" http://my.url/api.php". So I have no idea where it goes wrong...

**Comment by J-8** [comment]
Fixed. Error messages are precise now and also give a description of what happend at the backend.
