### ISSUE TITLE
not in f-droid anymore

### ISSUE THREAD

**Issue by tooka** [GroundApps/ShoppingList#64]
Hello everyone,

I can't find the app in the f-droid-store anymore. I guess it has been moved out of the main repository as the wiki shows two "Antifeatures"?
https://f-droid.org/wiki/page/org.janb.shoppinglist

I tried to build it with android studio but got this error:
Error:Unsupported method: BaseConfig.getApplicationIdSuffix().
The version of Gradle you connect to does not support that method.
To resolve the problem you can change/upgrade the target version of Gradle you connect to.
Alternatively, you can ignore this exception and read other information from the model.

This is where I got lost as answers from googleing showed only app specific results (not for shoppinglist).

Will ShoppingList be available in f-droid anytime soon?

Thank you very much for your help
Tom

**Comment by ghost** [comment]
Sorry this app isn't under active development.
We didn't find the time to do it.

**Comment by tooka** [comment]
O well that's a pity. And I'm not a skilled programmer either ;-)
But thank you for the work you've started. Helped me a lot.
